// Generates README.md and README_zh.md from data/emotions.json
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const data = JSON.parse(fs.readFileSync(path.join(ROOT, 'data', 'emotions.json'), 'utf8'));

const REPO = 'ai-video-emotion-guide';
const REF = `ref=${REPO}`;
const RAW = `https://raw.githubusercontent.com/useneospark/${REPO}/main`;

const FAMILY_ORDER = ['Joy', 'Surprise', 'Fear', 'Anger', 'Sadness', 'Disgust', 'Social', 'Drive', 'Physical'];
const FAMILY_ZH = {
  Joy: '喜悦', Surprise: '惊讶', Fear: '恐惧', Anger: '愤怒', Sadness: '悲伤',
  Disgust: '厌恶', Social: '社交', Drive: '驱动', Physical: '生理',
};
const NAME_ZH = {
  'Joy / Laughter': '喜悦 / 大笑', 'Shock': '震惊', 'Terror': '惊恐', 'Rage': '暴怒',
  'Disgust': '厌恶', 'Crying': '哭泣', 'Pain / Wince': '疼痛 / 龇牙', 'Eye Roll': '翻白眼',
  'Suspicion': '怀疑', 'Flirtation': '调情', 'Smug / Gloating': '得意 / 幸灾乐祸',
  'Boredom': '无聊', 'Confusion': '困惑', 'Realization': '恍然大悟', 'Awe / Wonder': '敬畏 / 惊叹',
  'Determination': '坚定', 'Frustration': '挫败', 'Anxiety': '焦虑', 'Sadness': '悲伤',
  'Guilt': '愧疚', 'Embarrassment': '尴尬', 'Exhaustion': '精疲力尽', 'Relief': '如释重负',
  'Pride': '自豪', 'Nervous Fake Smile': '紧张的假笑',
};
const INTENSITY_ZH = { Subtle: '细腻', Medium: '中等', Explosive: '爆发' };

const slug = (e) => e.videoSrc.split('/').pop().replace('.mp4', '');
const videoFile = (e) => `videos/${slug(e)}.mp4`;

const counts = {};
for (const e of data) counts[e.family] = (counts[e.family] || 0) + 1;

function entryEn(e, i) {
  const s = slug(e);
  return `### ${i + 1}. ${e.name}

> ${e.prompt}

**Family:** ${e.family} · **Intensity:** ${e.intensity} · **Cue:** ${e.cue}
**Aliases:** ${e.aliases}

🎬 [Watch performance video](${videoFile(e)}) · [**Try this direction on NeoSpark →**](https://useneospark.com/prompt-lib?prompt=${s}&${REF})
`;
}

function entryZh(e, i) {
  const s = slug(e);
  return `### ${i + 1}. ${NAME_ZH[e.name] || e.name}（${e.name}）

> ${e.prompt}

**情绪族：** ${FAMILY_ZH[e.family]} · **强度：** ${INTENSITY_ZH[e.intensity]} · **表演线索：** ${e.cue}
**检索别名：** ${e.aliases}

🎬 [观看表演视频](${videoFile(e)}) · [**在 NeoSpark 上使用这段导演指令 →**](https://useneospark.com/prompt-lib?prompt=${s}&${REF})
`;
}

function build(lang) {
  const zh = lang === 'zh';
  const L = zh ? {
    title: 'AI 视频情绪导演完全指南',
    tagline: '25 组可直接复制的 AI 视频情绪表演导演指令。',
    tagline2: '只描述看得见的表演：眼神、眉、嘴、呼吸、肩膀。不含场景、镜头、服装、剧情。',
    tryAll: '在 NeoSpark 上试用全部指令 →',
    quick: '快速导航',
    family: '情绪族', count: '数量', try: '在线生成',
    what: '什么是情绪导演指令？',
    whatBody: `**情绪导演指令（Emotion Direction）** 是一种只描述「可见表演行为」的提示词写法：眼部、眉毛、嘴型、呼吸、肩颈的物理动作，按时间顺序排列。\n\n它的原则：**表演与制作分离**。场景、镜头、服装、剧情、声音、时长全部留给你的主提示词，这条指令只负责情绪本身，可以附加在任何场景描述之后。\n\n每条指令都配有 Seedance 2.5 实际生成的表演参考视频。`,
    how: '使用方法',
    how1: '按情绪族和强度选择一条指令。',
    how2: '复制该条表演提示词（prompt）。',
    how3: '把它粘贴在你自己的场景描述和触发词之后，在 NeoSpark 生成。',
    example: '组合示例',
    exampleBody: '你的场景描述 + 情绪指令：',
    data: '结构化数据',
    dataBody: '全部 25 条指令的机器可读版本（name / family / intensity / cue / prompt / aliases / 视频地址）在 [`data/emotions.json`](data/emotions.json)，方便接入你自己的工作流。',
    source: '来源与致谢',
    sourceBody: '内容整理自 [Emotion Direction | Performance Prompt Library](https://seedance-emotion-direction.vercel.app/)，原始页面快照保存在 [`site/`](site/) 与 [`docs/site-text.md`](docs/site-text.md)。',
    contrib: '参与贡献',
    license: '许可证',
    licenseBody: '[CC BY 4.0](LICENSE) — 可自由分享与改编，需署名。',
    toc: '目录',
    videos: '视频说明',
    videosBody: '每个条目链接到仓库内 [`videos/`](videos/) 中的 mp4 参考表演（约 6.6MB，全部离线可用）。GitHub 上点击即可播放。',
    other: '其他语言',
  } : {
    title: 'The Complete AI Video Emotion Direction Guide',
    tagline: '25 copy-paste emotion performance directions for AI video.',
    tagline2: 'Only visible acting: eyes, brows, mouth, breath, shoulders. No scene, camera, wardrobe, or story.',
    tryAll: 'Try all directions on NeoSpark →',
    quick: 'Quick Links',
    family: 'Family', count: 'Prompts', try: 'Try on NeoSpark',
    what: 'What is Emotion Direction?',
    whatBody: `**Emotion direction** is a prompting style that describes only *visible acting behavior*: eyes, brows, mouth, breath, shoulders, in temporal order.\n\nThe principle: **keep performance separate from production**. Room, camera, wardrobe, story, audio and duration live in your own scene prompt — the direction covers only the emotion, and appends after any scene description.\n\nEvery direction ships with a reference performance generated by Seedance 2.5.`,
    how: 'How to Use',
    how1: 'Pick an emotion by family and intensity.',
    how2: 'Copy its performance prompt.',
    how3: 'Paste it after your own scene description and trigger, then generate on NeoSpark.',
    example: 'Combination Example',
    exampleBody: 'Your scene description + emotion direction:',
    data: 'Structured Data',
    dataBody: 'Machine-readable version of all 25 directions (name / family / intensity / cue / prompt / aliases / video URL) in [`data/emotions.json`](data/emotions.json) — ready for your own pipeline.',
    source: 'Source & Credits',
    sourceBody: 'Curated from [Emotion Direction | Performance Prompt Library](https://seedance-emotion-direction.vercel.app/). Original page snapshot kept in [`site/`](site/) and [`docs/site-text.md`](docs/site-text.md).',
    contrib: 'Contributing',
    license: 'License',
    licenseBody: '[CC BY 4.0](LICENSE) — free to share and adapt with attribution.',
    toc: 'Table of Contents',
    videos: 'About the Videos',
    videosBody: 'Each entry links to an mp4 reference performance inside [`videos/`](videos/) (~6.6MB total, fully offline). Click to play on GitHub.',
    other: 'Languages',
  };

  const otherLink = zh ? '<a href="README.md">English</a>' : '<a href="README_zh.md">中文</a>';
  const entry = zh ? entryZh : entryEn;

  let out = `<div align="center">

<h1>🎭 ${L.title}</h1>

<p>
  <a href="https://github.com/sindresorhus/awesome"><img src="https://awesome.re/badge.svg" alt="Awesome"></a>
  <img src="https://img.shields.io/badge/Prompts-25-blue.svg" alt="25 Prompts">
  <img src="https://img.shields.io/badge/Videos-25-purple.svg" alt="25 Videos">
  <img src="https://img.shields.io/badge/License-CC%20BY%204.0-lightgrey.svg" alt="License">
</p>

<p><b>${L.tagline}</b><br>
${L.tagline2}</p>

<p>
  <a href="https://useneospark.com/prompt-lib?${REF}"><b>${L.tryAll}</b></a> |
  ${otherLink}
</p>

</div>

---

## ${L.quick}

| ${L.family} | ${L.count} | ${L.try} |
|----------|---------|-----------------|
`;
  for (const f of FAMILY_ORDER) {
    const anchor = f.toLowerCase();
    const label = zh ? `${FAMILY_ZH[f]} ${f}` : f;
    out += `| [${label}](#${anchor}) | ${counts[f]} | [Generate](https://platform.useneospark.com/) |\n`;
  }
  out += `
---

## ${L.what}

${L.whatBody}

> ${zh ? '想直接生成带情绪表演的 AI 视频？' : 'Want to generate emotional AI video performances directly?'} **[NeoSpark](https://useneospark.com/?${REF})** ${zh ? '支持 Seedance 等视频模型，开箱即用。' : 'supports Seedance-class video models out of the box.'}

---

## ${L.how}

1. ${L.how1}
2. ${L.how2}
3. ${L.how3}

### ${L.example}

${L.exampleBody}

\`\`\`
A young woman in a rainy neon-lit alley, medium close-up.
${data[17].prompt}
\`\`\`

---

## ${L.toc}

`;
  for (const f of FAMILY_ORDER) {
    const label = zh ? `${FAMILY_ZH[f]} ${f}` : f;
    out += `- [${label}](#${f.toLowerCase()})\n`;
  }
  out += `- [${L.data}](#${zh ? '结构化数据' : 'structured-data'})\n- [${L.source}](#${zh ? '来源与致谢' : 'source--credits'})\n- [${L.contrib}](#${zh ? '参与贡献' : 'contributing'})\n- [${L.license}](#${zh ? '许可证' : 'license'})\n\n---\n`;

  let i = 0;
  for (const f of FAMILY_ORDER) {
    const label = zh ? `${FAMILY_ZH[f]} ${f}` : f;
    out += `\n## ${label}\n\n`;
    for (const e of data.filter(x => x.family === f)) {
      out += entry(e, i) + '\n';
      i++;
    }
  }

  out += `---

## ${L.data}

${L.dataBody}

## ${L.videos}

${L.videosBody}

## ${L.source}

${L.sourceBody}

## ${L.contrib}

${zh ? `欢迎提交 Pull Request 补充新的情绪指令。格式见 [docs/CONTRIBUTING.md](docs/CONTRIBUTING.md)。` : `Pull requests welcome for new emotion directions. Format: see [docs/CONTRIBUTING.md](docs/CONTRIBUTING.md).`}

## ${L.license}

${L.licenseBody}

---

<div align="center">
${zh ? '由' : 'Powered by'} <a href="https://useneospark.com/?${REF}"><b>NeoSpark</b></a> · <a href="https://platform.useneospark.com/">${zh ? '立即生成' : 'Start generating'}</a>
</div>
`;
  return out;
}

fs.writeFileSync(path.join(ROOT, 'README.md'), build('en'));
fs.writeFileSync(path.join(ROOT, 'README_zh.md'), build('zh'));
console.log('README.md + README_zh.md written,', data.length, 'entries');
